#!/usr/bin/python
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%               File name: testModel_run.py 
#%               last modified 2011-08-12
#%               2011 - David Malo Cid
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
# This script calls the make_OMscript.py and sim.py
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
# load modules
# --------------------------------------------------------------------------
import sys,os, random, time
global sweepVariable, jj, max_iter
max_iter = 7

now1= time.time()
#removing the simualtion files so that a fresh simualtion can start and in
#case of failure. Also changing the working directory
# --------------------------------------------------------------------------
os.chdir(r'D:\David\project\ParametricSweep')
os.system('del test_res.plt')
os.system('del ParametricSweep.plt')
os.system('del test_init.txt')
fileObject26=open('ParametricSweep.plt','a+',1)
fileObject26.write("#Ptolemy Plot file, generated by OpenModelica" + "\n")
fileObject26.write("#NumberofVariables=1" + "\n")
fileObject26.write("#IntervalSize=" + str(max_iter) + "\n")
fileObject26.write("TitleText: OpenModelica simulation plot" + "\n")
fileObject26.write("XLabel: Frequency" + "\n")
fileObject26.write("DataSet: Param_var" + "\n")
fileObject26.close()
# --------------------------------------------------------------------------
# Run OpenModelica Script
# --------------------------------------------------------------------------
for k in range(1,max_iter+1):
     jj=k
     sweepVariable = str(pow(10,jj))
     execfile('make_OMscript.py')
     os.popen(r"C:\OpenModelica1.7.0\bin\omc.exe test.mos").read()
     #Retrieving and restoring the result
     execfile('sim.py')

os.system(r'"C:\OpenModelica1.7.0\bin\OMPlot.exe --title=Parametric_Sweep --filename=ParametricSweep.plt --legend=true --grid=true --logx=false --logy=false --xlabel=Frequency --ylabel=Source_vAC --plot Param_var"')
import time
now2 = time.time()
print 'Time elapsed: '+ str(now2-now1)
